github.com:
<<<<<<< HEAD
    oauth_token: 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
=======
    oauth_token: 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
>>>>>>> origin/main
    user: rosacry
    git_protocol: https
